"""
Job Market Spider - Extracts job details from crawled URLs
"""

import csv
import logging
from datetime import datetime
import scrapy
from scrapy.http import HtmlResponse
from ..items import JobItem

logger = logging.getLogger(__name__)


class JobMarketSpider(scrapy.Spider):
    """Spider to extract job details from job board URLs."""
    
    name = 'job_market'
    allowed_domains = ['spotifyjobs.com', 'ashbyhq.com', 'greenhouse.io']
    
    def __init__(self, *args, **kwargs):
        """Initialize spider with URLs from CSV."""
        super(JobMarketSpider, self).__init__(*args, **kwargs)
        self.job_links = []
        self.load_job_links()
    
    def load_job_links(self, csv_file='data/raw/job_links.csv'):
        """Load job links from CSV file generated by Selenium."""
        try:
            with open(csv_file, 'r', encoding='utf-8') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    self.job_links.append(row)
            logger.info(f"Loaded {len(self.job_links)} job links from {csv_file}")
        except FileNotFoundError:
            logger.error(f"CSV file not found: {csv_file}")
            logger.error("Run Selenium extractor first: python run_project.py extract")
            raise
    
    def start_requests(self):
        """Generate requests for each job link."""
        for job in self.job_links:
            url = job.get('url')
            if url:
                yield scrapy.Request(
                    url=url,
                    callback=self.parse,
                    meta={
                        'original_title': job.get('title', ''),
                        'company_source': job.get('company', ''),
                        'source': job.get('source', '')
                    },
                    dont_obey_robotstxt=True
                )
    
    def parse(self, response):
        """Parse job detail page."""
        try:
            item = JobItem()
            
            # Get metadata from request
            item['job_title'] = response.meta.get('original_title', '')
            item['source'] = response.meta.get('source', '')
            item['job_url'] = response.url
            item['extracted_at'] = datetime.now().isoformat()
            item['last_updated'] = datetime.now().isoformat()
            
            # Extract company
            company = response.meta.get('company_source', '')
            if company:
                item['company'] = company
            else:
                # Try to extract from page
                item['company'] = self.extract_company(response)
            
            # Extract location
            item['location'] = self.extract_location(response)
            
            # Extract department
            item['department'] = self.extract_department(response)
            
            # Extract employment type
            item['employment_type'] = self.extract_employment_type(response)
            
            # Extract job description
            item['job_description'] = self.extract_job_description(response)
            
            # Extract requirements
            item['requirements'] = self.extract_requirements(response)
            
            # Extract posted date
            item['posted_date'] = self.extract_posted_date(response)
            
            if item.get('job_description'):
                yield item
            else:
                logger.warning(f"No description extracted from {response.url}")
        
        except Exception as e:
            logger.error(f"Error parsing {response.url}: {str(e)}")
    
    def extract_company(self, response):
        """Extract company name from page."""
        # Common company name selectors
        selectors = [
            '//meta[@property="og:site_name"]/@content',
            '//title/text()',
            '//h1/text()',
            '//div[@class*="company"]/text()',
        ]
        
        for selector in selectors:
            result = response.xpath(selector).get()
            if result:
                return result.strip()
        
        return 'Unknown'
    
    def extract_location(self, response):
        """Extract job location."""
        # Common location patterns
        selectors = [
            '//span[@class*="location"]/text()',
            '//div[@class*="location"]/text()',
            '//span[contains(text(), "Remote")] | //span[contains(text(), "Location")]/following-sibling::text()',
            '//dt[contains(text(), "Location")]/following-sibling::dd/text()',
        ]
        
        for selector in selectors:
            result = response.xpath(selector).getall()
            if result:
                location = ', '.join([loc.strip() for loc in result if loc.strip()])
                if location:
                    return location
        
        return 'Not Specified'
    
    def extract_department(self, response):
        """Extract job department/team."""
        selectors = [
            '//span[@class*="department"]/text()',
            '//div[@class*="department"]/text()',
            '//dt[contains(text(), "Department")]/following-sibling::dd/text()',
            '//dt[contains(text(), "Team")]/following-sibling::dd/text()',
        ]
        
        for selector in selectors:
            result = response.xpath(selector).get()
            if result:
                return result.strip()
        
        return 'Not Specified'
    
    def extract_employment_type(self, response):
        """Extract employment type (Full-time, Part-time, etc.)."""
        selectors = [
            '//span[@class*="employment"]/text()',
            '//span[@class*="type"]/text()',
            '//dt[contains(text(), "Employment Type")]/following-sibling::dd/text()',
        ]
        
        for selector in selectors:
            result = response.xpath(selector).get()
            if result:
                return result.strip()
        
        # Default guess
        return 'Full-time'
    
    def extract_job_description(self, response):
        """Extract job description/summary."""
        selectors = [
            '//div[@class*="description"]//text()',
            '//div[@class*="job-description"]//text()',
            '//section[@class*="description"]//text()',
            '//main//p//text()',
            '//body//text()',
        ]
        
        for selector in selectors:
            texts = response.xpath(selector).getall()
            if texts:
                description = ' '.join([text.strip() for text in texts if text.strip()])
                if len(description) > 100:
                    return description[:5000]  # Limit to 5000 chars
        
        return 'Description not available'
    
    def extract_requirements(self, response):
        """Extract job requirements."""
        selectors = [
            '//div[@class*="requirement"]//text()',
            '//section[@class*="requirement"]//text()',
            '//div[contains(text(), "Requirements")]/following-sibling::*//text()',
        ]
        
        for selector in selectors:
            texts = response.xpath(selector).getall()
            if texts:
                requirements = ' '.join([text.strip() for text in texts if text.strip()])
                if requirements:
                    return requirements[:2000]
        
        return ''
    
    def extract_posted_date(self, response):
        """Extract job posted date."""
        selectors = [
            '//span[@class*="date"]/text()',
            '//time/@datetime',
            '//time/text()',
            '//span[contains(text(), "Posted")]/following-sibling::text()',
            '//dt[contains(text(), "Posted")]/following-sibling::dd/text()',
        ]
        
        for selector in selectors:
            result = response.xpath(selector).get()
            if result:
                return result.strip()
        
        return 'Unknown'
